### Api products

/// REGISTRA UN PRODUCTO NUEVO
POST http://localhost:3000/api/products/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
Content-Type: application/json

{
    "name_product": "aguacate",
    "origin": "campo",
    "caliber":"mediano",
    "price": 10.25,
    "stock_initial": 1000,
    "stock_now": 180,
    "status": 0,
    "image": "../../../assets/images/noimagen.jpg"
}

###
/// EDITA UN PRODUCTO
PUT http://localhost:3000/api/products/edit/75
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
Content-Type: application/json

{
    "name_product": "aguacate",
    "origin": "refrigeracion",
    "caliber":"mediano",
    "price": 10.25,
    "stock_initial": 1000,
    "stock_now": 180,
    "status": 1,
    "image": "../../../assets/images/noimagen.jpg"
}

###
/// RECUPERA TODOS LOS PRODUCTOS ACTIVOS
GET http://localhost:3000/api/products/active/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
/// RECUPERA TODOS LOS PRODUCTOS MAS VENDIDOS
GET http://localhost:3000/api/products/sales/best
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
/// RECUPERA TODOS LOS PRODUCTOS
GET http://localhost:3000/api/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
/// RECUPERA PRODUCTO POR ID
GET http://localhost:3000/api/products/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
PUT http://localhost:3000/api/products/stockNow/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs


### Api clients ###################################################

/// RECUPERA TODOS LOS CLIENTES
GET http://localhost:3000/api/clients
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
/// RECUPERA TODOS LOS CLIENTES
GET http://localhost:3000/api/clients/buyers/best
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
/// RECUPERA TODOS LOS CLIENTES SEGUN ESTATUS DE ACTIVO
GET http://localhost:3000/api/clients/status/0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs


###
/// EDITA UN CLIENTE
PUT http://localhost:3000/api/clients/edit/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
Content-Type: application/json

{
"name_client":"antonio Meyer",
"mail_client":"hugoñeyér209@yahoo.com",
"direction": "HovenStrasse 31, 1. Switzerland",
"phone": "4178899274",
"status": 1
}

###
/// REGISTRA UN CLIENTE NUEVO
POST http://localhost:3000/api/register/clients
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
Content-Type: application/json

{
"name_client":"Hugo Meyer",
"mail_client":"hugomeyer@yahoo.es",
"direction": "HovenStrasse 31, 1. Switzerland",
"phone": "+4178899274"
}

### api orders #############################################

### 
/// RECUPERA TODOS LOS PEDIDOS
GET http://localhost:3000/api/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

### 
/// RECUPERA TODOS LOS PEDIDOS PAGINADOS
GET http://localhost:3000/api/orders/paginated/1/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

### 
/// RECUPERA TODOS LOS PEDIDOS POR STATUS Y PAGINADOS
GET http://localhost:3000/api/orders/status/denegado/1/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
/// RECUPERA UN PEDIDO POR ID
GET  http://localhost:3000/api/orders/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
///////////////////////////////////////////////////////////////////////////////////////////


###
/// EDITA UN PEDIDO  
PUT http://localhost:3000/api/orders/edit/40/jumarlinares@gmail.com
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
Content-Type: application/json

{
    "id_client": 1,
    "id_product": 10,
    "vol_sale": 5,
    "shipping": "palets incompleto",
    "meth_payment":"tarjeta",
    "price_sale": 0.2,
    "id_user": 2,
    "date_order": "2022-12-20",
    "status": "aceptado",
    "comment": "sin comentarios"
}
 


###
/// REGISTRA UN PEDIDO NUEVO
POST http://localhost:3000/api/orders/register/jumarlinares@gmail.com
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

{
    "id_client": 6,
    "id_product": 1,
    "vol_sale": 200,
    "shipping": "paquete",
    "meth_payment":"otros",
    "price_sale": 0.18,
    "id_user": 2,
    "date_order": "2022-11-10",
    "status": "pendiente",
    "comment": "revisar precio"
}


###
/// RECUPERA TODOS LOS PEDIDOS DE UN USUARIO
GET  http://localhost:3000/api/orders/user/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
 

###
/// RECUPERA TODOS LOS PEDIDOS DE UN PRODUCTO
GET  http://localhost:3000/api/orders/product/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs


###
/// RECUPERA TODOS LOS PEDIDOS DE POR UNA FECHA
GET  http://localhost:3000/api/orders/date/2022-07-09T22:00:00.000Z
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs


###
/// RECUPERA TODOS LOS PEDIDOS DE UN CLIENTE
GET  http://localhost:3000/api/orders/client/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
/// ENVIO MAIL PARA VALIDACION DE PEDIDOS
POST http://localhost:3000/api/orders/send-email/reminder/3/pendiente/jumarlinares@gmail.com
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs


###
/// RECUPERA TODOS LOS PEDIDOS CON NOMBRE Y VOLUMEN DEL PRODUCTO FILTRANDO POR FECHA
GET  http://localhost:3000/api/orders/sales/2022-05-01/2022-07-01
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
///////////////////////////////////////////////////////////////////////////////////////////

###
/// RECUPERA TODOS LOS PEDIDOS CON NOMBRE, PRECIO Y VOLUMEN DEL PRODUCTO FILTRANDO POR FECHA
GET  http://localhost:3000/api/orders/sales/price/2022-05-01/2022-07-01
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
///////////////////////////////////////////////////////////////////////////////////////////

###
/// RECUPERA EL N0MBRE DEL USUARIO CON MAYOR VENTA , CALCULA PRECIO TOTAL DE SUS VENTAS (€/KG)
GET http://localhost:3000/api/orders/user/best
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
///////////////////////////////////////////////////////////////////////////////////////////

###
/// RECUPERA TODOS LOS PEDIDOS FILTRANDO POR CLIENTE , PRODUCTO , FECHA Y PAGINADO
GET  http://localhost:3000/api/orders/sales/filter/1/3/2022-01-01/2022-11-30/1/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
///////////////////////////////////////////////////////////////////////////////////////////

###
/// RECUPERA TODOS LOS PEDIDOS FILTRANDO POR CLIENTE , PRODUCTO , FECHA, ESTADO PAGINADO
GET  http://localhost:3000/api/orders/sales/filter/status/6/10/pendiente/2022-01-01/2022-11-30/1/100
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
///////////////////////////////////////////////////////////////////////////////////////////

### Api users

GET http://localhost:3000/api/users/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM5LCJ1c2VyUm9sZSI6InVzZXIiLCJleHBpcmVzQXQiOjE2NzE4NTU1MzksImlhdCI6MTY2ODI1NTUzOX0.SPKuMAPu1GzsWd9m3c-Xe4s0OQcqg56w3c61UJz96Ro

###
/// RECUPERA TODOS LOS USUARIOS
GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
/// RECUPERA TODOS LOS USUARIOS por status
GET http://localhost:3000/api/users/status/0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
/// RECUPERA TODOS LOS USUARIOS
GET http://localhost:3000/api/users/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

###
///EDITA UN USUARIO
PUT http://localhost:3000/api/users/edit/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
Content-Type: application/json

{
    "name_user": "Jose",
    "surname_user":"Pizarroso",
    "mail_user":"ivanpizarroso@gmail.com",
    "password_user": "5534Ggr",
    "role": "AdmiN",
    "status": 1
}


###
/// REGISTRA UN USUARIO NUEVO
POST http://localhost:3000/api/users/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs
Content-Type: application/json

{
    "name_user": "Paco",
    "surname_user":"Pizarroso",
    "mail_user":"moartinpizarroso@gmail.com",
    "password_user": "5534Ggr",
    "role": "user",
    "status": 1
}

###
///EDITA UN PASSWORD
PUT http://localhost:3000/api/users/new-password/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs

{
    "password_user": "Admin123"
}
 
###
/// ENVIA UN EMAIL PARA CAMBIO DE PASSWORD
POST http://localhost:3000/api/users/send-email/recovery/jumarlinares@gmail.com
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs


///////////////////////////////////////////////////////

###
/// ENVIO IMAGENES DE PRODUCTO
POST http://localhost:3000/api/products/imagen1.jpg
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2LCJ1c2VyUm9sZSI6Im1hc3RlciIsImV4cGlyZXNBdCI6MTY3MTg1NTY5MywiaWF0IjoxNjY4MjU1NjkzfQ.c_-mBLI-lqN9gMQ-dWtsG47tJIHBe5nsg76kXGhTkCs


